name: Build and Release ESI.NET

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      manual_tag:
        description: 'Version tag (e.g. v1.2.3)'
        required: true

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_PLATFORM: 'Any CPU'
      BUILD_CONFIGURATION: 'Release'

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Extract version from tag or input
        id: get_version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.manual_tag }}" | sed 's/^v//' >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          fi

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: |
          dotnet build "**/*.sln" --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Pack project
        run: |
          dotnet pack ESI.NET/ESI.NET.csproj \
            --configuration ${{ env.BUILD_CONFIGURATION }} \
            --output ./nupkgs \
            /p:PackageVersion=${{ steps.get_version.outputs.version }}

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuget-package
          path: ./nupkgs/*.nupkg

  deploy:
    needs: build
    runs-on: windows-latest

    steps:
      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: nuget-package

      # - name: Push to NuGet.org
      #   run: |
      #     dotnet nuget push "nupkgs/*.nupkg" \
      #       --api-key ${{ secrets.NUGET_API_KEY }} \
      #       --source https://api.nuget.org/v3/index.json

      - name: Send Discord Webhook
        if: success()
        env:
          DISCORD_WEBHOOK: ${{ github.event_name == 'workflow_dispatch' && secrets.DISCORD_TEST_WEBHOOK_URL || secrets.DISCORD_WEBHOOK_URL }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            **ESI.NET ${{ steps.get_version.outputs.version }} Release**
            The build has completed successfully, and the NuGet package is now available.
            <https://github.com/seraphx2/ESI.NET/releases>
